# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFYV9RZ4tKhC_zTKaJiPOxksKSZqAmtz
"""

import numpy as np

class Particle:
    def __init__(self, num_nodes):
        self.position = np.random.rand(num_nodes)
        self.velocity = np.random.uniform(-0.1, 0.1, num_nodes)
        self.best_position = np.copy(self.position)
        self.best_distance = float('inf')

    def get_path(self):
        return np.argsort(self.position)

def calculate_total_distance(path, distance_matrix):
    distance = 0
    for i in range(len(path) - 1):
        distance += distance_matrix[path[i]][path[i+1]]
    distance += distance_matrix[path[-1]][path[0]]  # Complete the loop back to start
    return distance

def particle_swarm_optimization(distance_matrix, num_particles=30, max_iter=200):
    num_nodes = len(distance_matrix)

    # PSO Hyperparameters
    w, c1, c2 = 0.5, 1.5, 1.5

    swarm = [Particle(num_nodes) for _ in range(num_particles)]
    global_best_position = None
    global_best_distance = float('inf')

    for particle in swarm:
        path = particle.get_path()
        distance = calculate_total_distance(path, distance_matrix)
        particle.best_distance = distance
        if distance < global_best_distance:
            global_best_distance = distance
            global_best_position = np.copy(particle.position)

    for _ in range(max_iter):
        for particle in swarm:
            r1, r2 = np.random.rand(num_nodes), np.random.rand(num_nodes)
            cognitive = c1 * r1 * (particle.best_position - particle.position)
            social = c2 * r2 * (global_best_position - particle.position)
            particle.velocity = w * particle.velocity + cognitive + social
            particle.position += particle.velocity

            current_path = particle.get_path()
            current_distance = calculate_total_distance(current_path, distance_matrix)

            if current_distance < particle.best_distance:
                particle.best_distance = current_distance
                particle.best_position = np.copy(particle.position)

            if current_distance < global_best_distance:
                global_best_distance = current_distance
                global_best_position = np.copy(particle.position)

    best_path = np.argsort(global_best_position)
    return best_path, global_best_distance

# --- Interactive Input Handling ---
def get_user_input():
    print("Select Input Mode:")
    print("1. Enter Location Coordinates (X, Y)")
    print("2. Enter Custom Distance Matrix directly")
    choice = input("Enter choice (1 or 2): ").strip()

    num_nodes = int(input("Enter total number of locations/nodes: "))

    if choice == "1":
        # Scenario 1: Location Coordinates
        coordinates = []
        print("\nEnter coordinates format -> X Y (separated by a space):")
        for i in range(num_nodes):
            coord_str = input(f"Coordinates for Node {i}: ")
            x, y = map(float, coord_str.split())
            coordinates.append([x, y])

        # Calculate distance matrix from coordinates
        coordinates = np.array(coordinates)
        distance_matrix = np.zeros((num_nodes, num_nodes))
        for i in range(num_nodes):
            for j in range(num_nodes):
                distance_matrix[i][j] = np.linalg.norm(coordinates[i] - coordinates[j])
        return distance_matrix

    elif choice == "2":
        # Scenario 2: Direct Distance Matrix
        print("\nEnter distances row by row (space-separated values):")
        print("Example for a 3x3 matrix row: 0 15 20")
        distance_matrix = []
        for i in range(num_nodes):
            row_str = input(f"Row {i} distances: ")
            row = list(map(float, row_str.split()))
            if len(row) != num_nodes:
                raise ValueError(f"Each row must contain exactly {num_nodes} distances!")
            distance_matrix.append(row)
        return np.array(distance_matrix)
    else:
        print("Invalid choice. Restarting prompt...")
        return get_user_input()

if __name__ == "__main__":
    try:
        dist_matrix = get_user_input()

        print("\nRunning PSO Algorithm...")
        best_route, shortest_distance = particle_swarm_optimization(dist_matrix)

        print("\n" + "="*30)
        print(f"Optimal Path Sequence: {' -> '.join(map(str, best_route))} -> {best_route[0]}")
        print(f"Total Path Distance: {shortest_distance:.4f}")
        print("="*30)
    except Exception as e:
        print(f"An error occurred with inputs: {e}")