# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGrbi2aRJoJMBFH6lPQggOiKln2aFubZ
"""

import random


# ============================================================
# 1. INPUT DATA
# ============================================================

# Each class = (subject, faculty, student_group)

classes = [
    ("Mathematics", "Dr. Smith", "G1"),
    ("Physics", "Dr. John", "G1"),
    ("Programming", "Dr. Smith", "G2"),
    ("English", "Dr. Mary", "G2"),
    ("Database", "Dr. John", "G3"),
    ("Networks", "Dr. Mary", "G3"),
    ("AI", "Dr. Smith", "G4"),
    ("Operating Systems", "Dr. John", "G4")
]

# Available time slots
slots = [
    "Monday 9-11",
    "Monday 11-1",
    "Tuesday 9-11",
    "Tuesday 11-1",
    "Wednesday 9-11",
    "Wednesday 11-1"
]

# Available rooms
rooms = [
    "Room 101",
    "Room 102",
    "Room 103"
]


# ============================================================
# 2. GENETIC ALGORITHM PARAMETERS
# ============================================================

POPULATION_SIZE = 100
GENERATIONS = 1000

MUTATION_RATE = 0.10

TOURNAMENT_SIZE = 3

# If we reach zero conflicts, we can stop.
TARGET_CONFLICTS = 0


# ============================================================
# 3. CREATE A RANDOM CHROMOSOME
# ============================================================

def create_chromosome():
    """
    Create one random timetable.

    Each gene is:
        (slot_index, room_index)

    One gene corresponds to one class.
    """

    chromosome = []

    for _ in classes:

        slot = random.randrange(len(slots))
        room = random.randrange(len(rooms))

        chromosome.append((slot, room))

    return chromosome


# ============================================================
# 4. CREATE INITIAL POPULATION
# ============================================================

def create_population():
    population = []

    for _ in range(POPULATION_SIZE):
        chromosome = create_chromosome()
        population.append(chromosome)

    return population


# ============================================================
# 5. FITNESS FUNCTION
# ============================================================

def calculate_conflicts(chromosome):
    """
    Count the number of scheduling conflicts.

    Conflicts occur when two classes have the same time slot
    and share:

        1. Same faculty
        2. Same room
        3. Same student group
    """

    conflicts = 0

    # Compare every pair of classes
    for i in range(len(classes)):

        for j in range(i + 1, len(classes)):

            subject1, faculty1, group1 = classes[i]
            subject2, faculty2, group2 = classes[j]

            slot1, room1 = chromosome[i]
            slot2, room2 = chromosome[j]

            # Conflicts matter only if classes occur
            # at the same time.
            if slot1 == slot2:

                # Faculty conflict
                if faculty1 == faculty2:
                    conflicts += 1

                # Room conflict
                if room1 == room2:
                    conflicts += 1

                # Student group conflict
                if group1 == group2:
                    conflicts += 1

    return conflicts


def fitness(chromosome):
    """
    Fitness = 1 / (1 + number_of_conflicts)

    Fewer conflicts => higher fitness.

    If conflicts = 0:
        fitness = 1

    If conflicts = 1:
        fitness = 0.5

    If conflicts = 2:
        fitness = 0.333
    """

    conflicts = calculate_conflicts(chromosome)

    return 1 / (1 + conflicts)


# ============================================================
# 6. SELECTION
# ============================================================

def tournament_selection(population):
    """
    Select one chromosome using tournament selection.

    Randomly select a few chromosomes and return
    the one having the highest fitness.
    """

    tournament = random.sample(
        population,
        TOURNAMENT_SIZE
    )

    winner = max(
        tournament,
        key=fitness
    )

    return winner.copy()


# ============================================================
# 7. SINGLE-POINT CROSSOVER
# ============================================================

def single_point_crossover(parent1, parent2):
    """
    Perform single-point crossover.

    Example:

    Parent 1:
    A B C | D E F

    Parent 2:
    X Y Z | P Q R

    Child 1:
    A B C | P Q R

    Child 2:
    X Y Z | D E F
    """

    # Random crossover position
    point = random.randint(1, len(parent1) - 1)

    child1 = (
        parent1[:point] +
        parent2[point:]
    )

    child2 = (
        parent2[:point] +
        parent1[point:]
    )

    return child1, child2


# ============================================================
# 8. MUTATION
# ============================================================

def mutation(chromosome):
    """
    Mutation randomly changes the slot or room of a class.

    According to the problem:
        mutation reassigns a random slot or room.
    """

    mutated = chromosome.copy()

    for i in range(len(mutated)):

        # Decide whether this gene should mutate
        if random.random() < MUTATION_RATE:

            slot, room = mutated[i]

            # Randomly choose whether to change
            # slot or room.

            if random.random() < 0.5:

                # Change time slot
                slot = random.randrange(len(slots))

            else:

                # Change room
                room = random.randrange(len(rooms))

            mutated[i] = (slot, room)

    return mutated


# ============================================================
# 9. GET BEST CHROMOSOME
# ============================================================

def get_best(population):

    return max(
        population,
        key=fitness
    )


# ============================================================
# 10. GENETIC ALGORITHM
# ============================================================

def genetic_algorithm():

    # Create initial population
    population = create_population()

    best_solution = None
    best_fitness = -1

    for generation in range(GENERATIONS):

        new_population = []

        # Keep the best chromosome (elitism)
        current_best = get_best(population)

        current_fitness = fitness(current_best)

        if current_fitness > best_fitness:

            best_solution = current_best.copy()
            best_fitness = current_fitness

        # Check whether a conflict-free timetable exists
        if calculate_conflicts(current_best) == TARGET_CONFLICTS:

            print(
                f"Solution found at generation "
                f"{generation}"
            )

            return current_best

        # Elitism
        new_population.append(current_best.copy())

        # Create new generation
        while len(new_population) < POPULATION_SIZE:

            # Selection
            parent1 = tournament_selection(population)
            parent2 = tournament_selection(population)

            # Crossover
            child1, child2 = single_point_crossover(
                parent1,
                parent2
            )

            # Mutation
            child1 = mutation(child1)
            child2 = mutation(child2)

            # Add children
            new_population.append(child1)

            if len(new_population) < POPULATION_SIZE:
                new_population.append(child2)

        population = new_population

        # Display progress
        if generation % 50 == 0:

            conflicts = calculate_conflicts(current_best)

            print(
                f"Generation: {generation}, "
                f"Conflicts: {conflicts}, "
                f"Fitness: {current_fitness:.4f}"
            )

    return best_solution


# ============================================================
# 11. DISPLAY FINAL TIMETABLE
# ============================================================

def display_timetable(chromosome):

    print("\n")
    print("=" * 80)
    print("FINAL CLASS TIMETABLE")
    print("=" * 80)

    print(
        f"{'Subject':<20}"
        f"{'Faculty':<15}"
        f"{'Group':<10}"
        f"{'Time Slot':<20}"
        f"{'Room':<15}"
    )

    print("-" * 80)

    for i, class_info in enumerate(classes):

        subject, faculty, group = class_info

        slot_index, room_index = chromosome[i]

        print(
            f"{subject:<20}"
            f"{faculty:<15}"
            f"{group:<10}"
            f"{slots[slot_index]:<20}"
            f"{rooms[room_index]:<15}"
        )

    print("=" * 80)

    conflicts = calculate_conflicts(chromosome)

    print(f"Total conflicts : {conflicts}")
    print(f"Fitness         : {fitness(chromosome):.4f}")


# ============================================================
# 12. MAIN PROGRAM
# ============================================================

if __name__ == "__main__":

    best_solution = genetic_algorithm()

    display_timetable(best_solution)

import random

def get_input():

    print("=" * 60)
    print("       CLASS TIMETABLE SCHEDULING USING GA")
    print("=" * 60)

    n_classes = int(input("\nEnter number of classes: "))

    classes = []

    print("\nEnter details for each class")
    print("-" * 60)

    for i in range(n_classes):

        print(f"\nClass {i + 1}")

        subject = input("Enter subject name: ")
        faculty = input("Enter faculty name: ")
        group = input("Enter student group: ")

        classes.append(
            (subject, faculty, group)
        )


    n_slots = int(input("\nEnter number of time slots: "))

    slots = []

    print("\nEnter time slots:")

    for i in range(n_slots):

        slot = input(f"Slot {i + 1}: ")

        slots.append(slot)

    n_rooms = int(input("\nEnter number of rooms: "))

    rooms = []

    print("\nEnter room names:")

    for i in range(n_rooms):

        room = input(f"Room {i + 1}: ")

        rooms.append(room)

    return classes, slots, rooms


def get_ga_parameters():

    print("\n" + "=" * 60)
    print("GENETIC ALGORITHM PARAMETERS")
    print("=" * 60)

    population_size = int(
        input("Enter population size: ")
    )

    generations = int(
        input("Enter maximum number of generations: ")
    )

    mutation_rate = float(
        input("Enter mutation rate (0-1): ")
    )

    tournament_size = int(
        input("Enter tournament size: ")
    )

    return (
        population_size,
        generations,
        mutation_rate,
        tournament_size
    )


def create_chromosome(classes, slots, rooms):

    chromosome = []

    for _ in classes:


        slot = random.randrange(len(slots))


        room = random.randrange(len(rooms))

        chromosome.append(
            (slot, room)
        )

    return chromosome


def create_population(
    classes,
    slots,
    rooms,
    population_size
):

    population = []

    for _ in range(population_size):

        chromosome = create_chromosome(
            classes,
            slots,
            rooms
        )

        population.append(chromosome)

    return population


def calculate_conflicts(
    chromosome,
    classes
):

    conflicts = 0


    for i in range(len(classes)):

        for j in range(i + 1, len(classes)):

            subject1, faculty1, group1 = classes[i]
            subject2, faculty2, group2 = classes[j]

            slot1, room1 = chromosome[i]
            slot2, room2 = chromosome[j]


            if slot1 == slot2:

                if faculty1 == faculty2:

                    conflicts += 1

                if room1 == room2:

                    conflicts += 1

                if group1 == group2:

                    conflicts += 1

    return conflicts

def fitness(
    chromosome,
    classes
):

    conflicts = calculate_conflicts(
        chromosome,
        classes
    )


    return 1 / (1 + conflicts)

def tournament_selection(
    population,
    classes,
    tournament_size
):


    tournament = random.sample(
        population,
        tournament_size
    )


    winner = max(
        tournament,
        key=lambda chromosome:
        fitness(chromosome, classes)
    )

    return winner.copy()


def single_point_crossover(
    parent1,
    parent2
):


    point = random.randint(
        1,
        len(parent1) - 1
    )

    child1 = (
        parent1[:point] +
        parent2[point:]
    )

    child2 = (
        parent2[:point] +
        parent1[point:]
    )

    return child1, child2

def mutation(
    chromosome,
    slots,
    rooms,
    mutation_rate
):

    mutated = chromosome.copy()

    for i in range(len(mutated)):


        if random.random() < mutation_rate:

            slot, room = mutated[i]



            if random.random() < 0.5:


                slot = random.randrange(
                    len(slots)
                )

            else:


                room = random.randrange(
                    len(rooms)
                )

            mutated[i] = (
                slot,
                room
            )

    return mutated


def get_best(
    population,
    classes
):

    return max(
        population,
        key=lambda chromosome:
        fitness(chromosome, classes)
    )

def genetic_algorithm(
    classes,
    slots,
    rooms,
    population_size,
    generations,
    mutation_rate,
    tournament_size
):

    population = create_population(
        classes,
        slots,
        rooms,
        population_size
    )

    best_solution = None
    best_fitness = -1

    for generation in range(generations):


        current_best = get_best(
            population,
            classes
        )

        current_fitness = fitness(
            current_best,
            classes
        )

        current_conflicts = calculate_conflicts(
            current_best,
            classes
        )

        if current_fitness > best_fitness:

            best_solution = current_best.copy()

            best_fitness = current_fitness

        if current_conflicts == 0:

            print(
                f"\nSolution found at generation "
                f"{generation + 1}!"
            )

            return current_best

        new_population = []

        new_population.append(
            current_best.copy()
        )

        while len(new_population) < population_size:

            parent1 = tournament_selection(
                population,
                classes,
                tournament_size
            )

            parent2 = tournament_selection(
                population,
                classes,
                tournament_size
            )


            child1, child2 = single_point_crossover(
                parent1,
                parent2
            )

            child1 = mutation(
                child1,
                slots,
                rooms,
                mutation_rate
            )

            child2 = mutation(
                child2,
                slots,
                rooms,
                mutation_rate
            )

            new_population.append(child1)

            if len(new_population) < population_size:

                new_population.append(child2)

        population = new_population


        if (
            generation % 50 == 0
            or generation == generations - 1
        ):

            print(
                f"Generation {generation + 1:4d} | "
                f"Conflicts: {current_conflicts:3d} | "
                f"Fitness: {current_fitness:.4f}"
            )

    return best_solution


def display_timetable(
    chromosome,
    classes,
    slots,
    rooms
):

    print("\n")
    print("=" * 90)
    print("                 FINAL TIMETABLE")
    print("=" * 90)

    print(
        f"{'No.':<5}"
        f"{'Subject':<20}"
        f"{'Faculty':<20}"
        f"{'Group':<12}"
        f"{'Time Slot':<20}"
        f"{'Room':<15}"
    )

    print("-" * 90)

    for i, class_info in enumerate(classes):

        subject, faculty, group = class_info

        slot_index, room_index = chromosome[i]

        print(
            f"{i + 1:<5}"
            f"{subject:<20}"
            f"{faculty:<20}"
            f"{group:<12}"
            f"{slots[slot_index]:<20}"
            f"{rooms[room_index]:<15}"
        )

    print("=" * 90)

    conflicts = calculate_conflicts(
        chromosome,
        classes
    )

    final_fitness = fitness(
        chromosome,
        classes
    )

    print(f"Total conflicts : {conflicts}")
    print(f"Fitness         : {final_fitness:.4f}")

    if conflicts == 0:

        print(
            "\nStatus: CONFLICT-FREE TIMETABLE"
        )

    else:

        print(
            "\nStatus: Some conflicts remain."
        )

def main():

    classes, slots, rooms = get_input()


    (
        population_size,
        generations,
        mutation_rate,
        tournament_size
    ) = get_ga_parameters()



    if len(slots) == 0:

        print("Error: At least one time slot is required.")
        return

    if len(rooms) == 0:

        print("Error: At least one room is required.")
        return

    if population_size < 2:

        print(
            "Error: Population size must be at least 2."
        )

        return

    if tournament_size > population_size:

        print(
            "Error: Tournament size cannot be "
            "larger than population size."
        )

        return

    if not 0 <= mutation_rate <= 1:

        print(
            "Error: Mutation rate must be between 0 and 1."
        )

        return

    print("\n")
    print("=" * 60)
    print("RUNNING GENETIC ALGORITHM...")
    print("=" * 60)

    best_solution = genetic_algorithm(
        classes,
        slots,
        rooms,
        population_size,
        generations,
        mutation_rate,
        tournament_size
    )


        best_solution,
        classes,
        slots,
        rooms
    )




if __name__ == "__main__":

    main()